#!/usr/bin/env node
// Replaces: manual export → manual rename → manual copy-in → hand-typed manifest entry.
//
// What it does:
//   1. Reads a Figma page, finds top-level frames
//   2. Exports each as a 2x PNG (quality gate you already use)
//   3. Saves to public/media/case-studies/<slug>/<kebab-case-frame-name>.png
//   4. Writes/updates content/case-studies/<slug>.manifest.ts with draft entries
//      (alt text marked "VERIFY: <frame name>", same convention as your existing workflow)
//
// Setup:
//   export FIGMA_TOKEN="figd_..."          (Figma → Settings → Personal access tokens)
//
// Usage:
//   node scripts/figma-export.mjs <fileKey> <pageName> <case-study-slug>
//   node scripts/figma-export.mjs qCXIVqLucwu9dUCrnfpZQ8 "MVP 1/1/25" ai-assistant-2025

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "fs";
import path from "path";

const [fileKey, pageName, slug] = process.argv.slice(2);
const TOKEN = process.env.FIGMA_TOKEN;

if (!fileKey || !pageName || !slug) {
  console.error("Usage: node scripts/figma-export.mjs <fileKey> <pageName> <slug>");
  process.exit(1);
}
if (!TOKEN) {
  console.error("Missing FIGMA_TOKEN env var.");
  process.exit(1);
}

const HEADERS = { "X-Figma-Token": TOKEN };
const OUT_DIR = path.resolve("public/media/case-studies", slug);
const MANIFEST_PATH = path.resolve("content/case-studies", `${slug}.manifest.ts`);

const toKebab = (name) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

async function main() {
  console.log(`Fetching file tree for ${fileKey}...`);
  const fileRes = await fetch(`https://api.figma.com/v1/files/${fileKey}`, {
    headers: HEADERS,
  });
  if (!fileRes.ok) throw new Error(`Figma file fetch failed: ${fileRes.status}`);
  const fileData = await fileRes.json();

  const page = fileData.document.children.find((p) => p.name === pageName);
  if (!page) {
    console.error(`Page "${pageName}" not found. Available pages:`);
    fileData.document.children.forEach((p) => console.error(`  - ${p.name}`));
    process.exit(1);
  }

  // Top-level frames only — matches how you organize named screens per page.
  const frames = page.children.filter((n) => n.type === "FRAME");
  if (!frames.length) {
    console.error(`No frames found on page "${pageName}".`);
    process.exit(1);
  }
  console.log(`Found ${frames.length} frame(s): ${frames.map((f) => f.name).join(", ")}`);

  console.log("Requesting 2x PNG exports...");
  const ids = frames.map((f) => f.id).join(",");
  const imgRes = await fetch(
    `https://api.figma.com/v1/images/${fileKey}?ids=${ids}&scale=2&format=png`,
    { headers: HEADERS }
  );
  if (!imgRes.ok) throw new Error(`Figma image export failed: ${imgRes.status}`);
  const { images } = await imgRes.json();

  mkdirSync(OUT_DIR, { recursive: true });

  // Load or start a manifest object (as plain JS to append to, then serialize back to TS).
  let existingEntries = {};
  if (existsSync(MANIFEST_PATH)) {
    console.log(`Existing manifest found at ${MANIFEST_PATH} — appending new entries.`);
    // Lightweight extraction: pull the object literal back out for merging.
    // (For a from-scratch run this block is skipped.)
    const src = readFileSync(MANIFEST_PATH, "utf8");
    const match = src.match(/=\s*({[\s\S]*});?\s*$/);
    if (match) {
      try {
        existingEntries = eval(`(${match[1]})`);
      } catch {
        console.warn("Could not parse existing manifest — will overwrite.");
      }
    }
  }

  for (const frame of frames) {
    const url = images[frame.id];
    if (!url) {
      console.warn(`No export URL for frame "${frame.name}" — skipping.`);
      continue;
    }

    const kebabName = `${slug}-${toKebab(frame.name)}`;
    const filename = `${kebabName}.png`;
    const filePath = path.join(OUT_DIR, filename);

    const imgBuf = await (await fetch(url)).arrayBuffer();
    writeFileSync(filePath, Buffer.from(imgBuf));
    console.log(`  ✓ ${filename}`);

    existingEntries[kebabName] = {
      id: kebabName,
      src: `/media/case-studies/${slug}/${filename}`,
      alt: `VERIFY: ${frame.name.replace(/-/g, " ")}`,
      layout: frame.absoluteBoundingBox.width > frame.absoluteBoundingBox.height * 1.3
        ? "full"
        : "inset",
      width: Math.round(frame.absoluteBoundingBox.width * 2),
      height: Math.round(frame.absoluteBoundingBox.height * 2),
      status: "draft",
    };
  }

  const exportName = `${slug.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Images`;
  const body =
    `import type { ImageManifest } from "../../src/types/image-manifest";\n\n` +
    `// Auto-generated by scripts/figma-export.mjs — entries marked status: "draft"\n` +
    `// need alt text reviewed against the real pixels before ship.\n\n` +
    `export const ${exportName}: ImageManifest = ${JSON.stringify(existingEntries, null, 2)};\n`;

  mkdirSync(path.dirname(MANIFEST_PATH), { recursive: true });
  writeFileSync(MANIFEST_PATH, body);
  console.log(`\n✓ Manifest written to ${MANIFEST_PATH}`);
  console.log(`  Remember: register "${exportName}" in src/components/Img.tsx's REGISTRY.`);
  console.log(`  Then run: node scripts/validate-images.mjs`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
